# Generated by Django 5.2.4 on 2025-07-24 20:38

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('renewal_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_lost', models.BooleanField(db_index=True, default=False)),
                ('is_damaged', models.BooleanField(default=False, verbose_name='Sách bị hỏng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='inventory.book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_records', to='inventory.librarybus', verbose_name='Nơi lấy sách')),
                ('return_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_records', to='inventory.librarybus', verbose_name='Nơi trả sách')),
                ('staff_processed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_borrows', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xử lý')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử Mượn sách',
                'verbose_name_plural': 'Lịch sử Mượn sách',
                'ordering': ['-borrow_date'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='BulkTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('transaction_type', models.CharField(choices=[('bulk_return', 'Trả hàng loạt'), ('bulk_renew', 'Gia hạn hàng loạt'), ('bulk_fine', 'Tính phạt hàng loạt')], db_index=True, max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('processing_log', models.JSONField(blank=True, default=dict)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giao dịch hàng loạt',
                'verbose_name_plural': 'Giao dịch hàng loạt',
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='FinePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('credit_card', 'Thẻ tín dụng')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('refunded', 'Đã hoàn')], db_index=True, default='completed', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('gateway_reference', models.CharField(blank=True, max_length=100, verbose_name='Mã tham chiếu gateway')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú thanh toán')),
                ('borrow_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.borrowrecord')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xử lý')),
            ],
            options={
                'verbose_name': 'Thanh toán phạt',
                'verbose_name_plural': 'Thanh toán phạt',
                'ordering': ['-payment_date'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='ShippingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^(\\+84|0)[0-9]{9,10}$')])),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('processing', 'Đang chuẩn bị'), ('shipped', 'Đang giao'), ('delivered', 'Đã giao'), ('failed', 'Giao thất bại'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20)),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('shipping_partner', models.CharField(blank=True, choices=[('ghn', 'Giao Hàng Nhanh'), ('viettel', 'Viettel Post'), ('vnpost', 'VN Post')], max_length=50, verbose_name='Đối tác giao hàng')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Dự kiến giao hàng')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao thực tế')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Ghi chú giao hàng')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_requests', to='inventory.book')),
                ('borrow_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_request', to='transactions.borrowrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu giao sách',
                'verbose_name_plural': 'Các yêu cầu giao sách',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('expires_date', models.DateField(db_index=True)),
                ('is_fulfilled', models.BooleanField(db_index=True, default=False)),
                ('fulfilled_date', models.DateTimeField(blank=True, null=True)),
                ('queue_position', models.PositiveIntegerField(default=1)),
                ('notification_sent', models.BooleanField(db_index=True, default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.book')),
                ('preferred_pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.librarybus', verbose_name='Nơi nhận ưu tiên')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đặt trước sách',
                'verbose_name_plural': 'Đặt trước sách',
                'ordering': ['queue_position', 'created_at'],
                'indexes': [models.Index(fields=['book', 'is_fulfilled', 'queue_position'], name='transaction_book_id_fcd1a9_idx'), models.Index(fields=['user', 'is_fulfilled'], name='transaction_user_id_4bfc50_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_fulfilled', False)), fields=('user', 'book'), name='unique_active_reservation')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['user', 'return_date'], name='transaction_user_id_7df961_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['book', 'borrow_date'], name='transaction_book_id_7f1afc_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['due_date', 'return_date'], name='transaction_due_dat_6886e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('return_date__isnull', True)), fields=('user', 'book'), name='unique_active_borrow'),
        ),
        migrations.AddIndex(
            model_name='finepayment',
            index=models.Index(fields=['payment_status', 'payment_date'], name='transaction_payment_0d227f_idx'),
        ),
        migrations.AddIndex(
            model_name='finepayment',
            index=models.Index(fields=['borrow_record', 'payment_status'], name='transaction_borrow__c55464_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrequest',
            index=models.Index(fields=['status', 'created_at'], name='transaction_status_502327_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrequest',
            index=models.Index(fields=['user', 'status'], name='transaction_user_id_6e3872_idx'),
        ),
    ]
