# Generated by Django 5.2.4 on 2025-07-24 20:36

import blog.models
import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Tên chuyên mục')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Đường dẫn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('color_code', models.CharField(blank=True, default='#007bff', max_length=7, verbose_name='Mã màu')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon CSS class')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Thứ tự')),
                ('post_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Số bài viết')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Nổi bật')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.blogcategory', verbose_name='Chuyên mục cha')),
            ],
            options={
                'verbose_name': 'Chuyên mục Blog',
                'verbose_name_plural': 'Chuyên mục Blog',
                'ordering': ['sort_order', 'name'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Tên tag')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Mô tả')),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Số lần dùng')),
                ('is_trending', models.BooleanField(db_index=True, default=False, verbose_name='Xu hướng')),
            ],
            options={
                'verbose_name': 'Tag Blog',
                'verbose_name_plural': 'Tag Blog',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['slug'], name='blog_blogta_slug_7db848_idx'), models.Index(fields=['-usage_count'], name='blog_blogta_usage_c_c9cce3_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, verbose_name='Đã xác nhận')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng')], default='weekly', max_length=10, verbose_name='Tần suất')),
                ('categories', models.ManyToManyField(blank=True, to='blog.blogcategory', verbose_name='Chuyên mục')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Đường dẫn')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ngày xuất bản')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=blog.models.post_image_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Ảnh bìa')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Lượt xem')),
                ('like_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Lượt thích')),
                ('comment_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Số bình luận')),
                ('reading_time', models.PositiveSmallIntegerField(default=1, verbose_name='Thời gian đọc (phút)')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Nổi bật')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='Ghim')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Cho phép bình luận')),
                ('content_type', models.CharField(choices=[('article', 'Bài viết'), ('review', 'Đánh giá'), ('interview', 'Phỏng vấn'), ('tutorial', 'Hướng dẫn'), ('news', 'Tin tức')], db_index=True, default='article', max_length=20, verbose_name='Loại nội dung')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('pending', 'Chờ duyệt'), ('published', 'Đã xuất bản'), ('rejected', 'Bị từ chối'), ('archived', 'Lưu trữ')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('moderation_note', models.TextField(blank=True, verbose_name='Ghi chú duyệt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.blogcategory', verbose_name='Chuyên mục')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_posts', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Bài viết Blog',
                'verbose_name_plural': 'Bài viết Blog',
                'ordering': ['-is_pinned', '-publish_date', '-created_at'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('content', models.TextField(max_length=1000)),
                ('is_approved', models.BooleanField(default=True, verbose_name='Đã duyệt')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='Bình luận cha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_blog_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['created_at'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thích bài viết',
                'verbose_name_plural': 'Thích bài viết',
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='PostRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Điểm')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá bài viết',
                'verbose_name_plural': 'Đánh giá bài viết',
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('read_duration', models.PositiveIntegerField(default=0, verbose_name='Thời gian đọc (giây)')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_views', to='blog.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lượt xem',
                'verbose_name_plural': 'Lượt xem',
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug'], name='blog_blogca_slug_465e50_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['parent', 'sort_order'], name='blog_blogca_parent__2395e8_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['-post_count'], name='blog_blogca_post_co_4095ff_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['email', 'is_confirmed'], name='blog_newsle_email_532a12_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'publish_date'], name='blog_post_status_8279bd_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status'], name='blog_post_author__95cbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-view_count'], name='blog_post_view_co_3832f4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-like_count'], name='blog_post_like_co_aba8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured', 'status'], name='blog_post_is_feat_203193_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_type', 'status'], name='blog_post_content_24aba2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug', 'status'], name='blog_post_slug_714acb_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='blog_post_created_45f0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'user'], name='blog_postli_post_id_641af3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='postrating',
            index=models.Index(fields=['post', 'score'], name='blog_postra_post_id_d32224_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postrating',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post', 'created_at'], name='blog_postvi_post_id_2e6acd_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['ip_address', 'created_at'], name='blog_postvi_ip_addr_7bbdfc_idx'),
        ),
    ]
