# Generated by Django 5.2.2 on 2026-07-29 11:33

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_comment'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_alter_book_publication_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rating', models.DecimalField(choices=[(0.5, '0.5 sao'), (1.0, '1.0 sao'), (1.5, '1.5 sao'), (2.0, '2.0 sao'), (2.5, '2.5 sao'), (3.0, '3.0 sao'), (3.5, '3.5 sao'), (4.0, '4.0 sao'), (4.5, '4.5 sao'), (5.0, '5.0 sao')], decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)], verbose_name='Đánh giá')),
                ('review_text', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nội dung đánh giá')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề đánh giá')),
                ('is_spoiler', models.BooleanField(db_index=True, default=False, verbose_name='Có spoiler')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Đã xuất bản')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Đã xác thực')),
                ('helpful_votes', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Lượt hữu ích')),
                ('unhelpful_votes', models.PositiveIntegerField(default=0, verbose_name='Lượt không hữu ích')),
                ('reading_progress', models.CharField(choices=[('completed', 'Đã đọc xong'), ('reading', 'Đang đọc'), ('dnf', 'Không đọc nữa')], default='completed', max_length=20, verbose_name='Tiến độ đọc')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10, verbose_name='Trạng thái duyệt')),
                ('report_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('helpfulness_score', models.FloatField(db_index=True, default=0.0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá sách',
                'verbose_name_plural': 'Đánh giá sách',
                'ordering': ['-helpfulness_score', '-created_at'],
                'permissions': [('can_moderate', 'Can moderate reviews')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nội dung')),
                ('is_approved', models.BooleanField(db_index=True, default=True, verbose_name='Đã duyệt')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Được ghim')),
                ('likes_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Lượt thích')),
                ('depth', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('thread_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_community_comments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['-is_pinned', '-created_at'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thích bình luận',
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('verb', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_object_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_action', to='contenttypes.contenttype')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_target', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Nội dung xúc phạm'), ('inappropriate', 'Không phù hợp'), ('copyright', 'Vi phạm bản quyền'), ('other', 'Khác')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewed', 'Đã xử lý')], db_index=True, default='pending', max_length=10)),
                ('moderator_notes', models.TextField(blank=True)),
                ('object_id', models.CharField(max_length=36)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('is_helpful', models.BooleanField(verbose_name='Có hữu ích')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='blog.bookreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote đánh giá',
                'verbose_name_plural': 'Vote đánh giá',
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', 'is_published', 'rating'], name='blog_bookre_book_id_09b849_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['user', 'created_at'], name='blog_bookre_user_id_45b61c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['helpful_votes', 'created_at'], name='blog_bookre_helpful_038a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['moderation_status', 'created_at'], name='blog_bookre_moderat_c1b53e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['helpfulness_score'], name='blog_bookre_helpful_90b7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['report_count'], name='blog_bookre_report__808831_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'is_approved', 'parent'], name='blog_commen_post_id_50ce9a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='blog_commen_author__9faedb_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['thread_id', 'depth'], name='blog_commen_thread__139644_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['likes_count'], name='blog_commen_likes_c_bc374c_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', 'user'], name='blog_commen_comment_addc72_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['user', 'created_at'], name='blog_commen_user_id_aa1131_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='blog_notifi_recipie_e62f77_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='blog_report_content_c6f1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='blog_report_status_df2204_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpfulness',
            index=models.Index(fields=['review', 'is_helpful'], name='blog_review_review__202045_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpfulness',
            index=models.Index(fields=['user', 'created_at'], name='blog_review_user_id_0e94e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulness',
            unique_together={('user', 'review')},
        ),
    ]
