# Generated by Django 5.2.4 on 2026-08-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bookreview_comment_commentlike_notification_report_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
