# Generated by Django 5.2.2 on 2026-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='thread_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
