# Generated by Django 5.2.4 on 2026-08-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_thread_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewHelpfulness',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
