# Generated by Django 5.2.2 on 2026-07-29 13:43

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_book_publication_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedUserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activity_type', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('original_created_at', models.DateTimeField()),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hoạt động lưu trữ',
                'verbose_name_plural': 'Hoạt động lưu trữ',
                'ordering': ['-original_created_at'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='BusAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('total_borrows', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('efficiency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='inventory.librarybus')),
            ],
            options={
                'verbose_name': 'Thống kê xe bus',
                'verbose_name_plural': 'Thống kê xe bus',
                'ordering': ['-efficiency_score'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('total_borrows', models.PositiveIntegerField(default=0)),
                ('total_returns', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_searches', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Thống kê hàng ngày',
                'verbose_name_plural': 'Thống kê hàng ngày',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_db3351_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='BookAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('total_borrows', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('trend_direction', models.CharField(choices=[('up', 'Tăng'), ('down', 'Giảm'), ('stable', 'Ổn định')], default='stable', max_length=10)),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_borrowed', models.DateTimeField(blank=True, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='inventory.book')),
            ],
            options={
                'verbose_name': 'Thống kê sách',
                'verbose_name_plural': 'Thống kê sách',
                'ordering': ['-popularity_score', '-total_borrows'],
                'indexes': [models.Index(fields=['popularity_score'], name='analytics_b_popular_246d96_idx'), models.Index(fields=['total_borrows'], name='analytics_b_total_b_321c6e_idx'), models.Index(fields=['last_borrowed'], name='analytics_b_last_bo_d9e2cc_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('algorithm_type', models.CharField(choices=[('popular', 'Phổ biến'), ('similar_users', 'Người dùng tương tự'), ('same_category', 'Cùng thể loại'), ('trending', 'Xu hướng'), ('personalized', 'Cá nhân hóa')], default='popular', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('borrowed_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gợi ý sách',
                'verbose_name_plural': 'Gợi ý sách',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='analytics_b_user_id_f26325_idx'), models.Index(fields=['score'], name='analytics_b_score_ae0f41_idx'), models.Index(fields=['algorithm_type'], name='analytics_b_algorit_f8dcaa_idx')],
                'unique_together': {('user', 'book')},
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('activity_type', models.CharField(choices=[('borrow', 'Mượn sách'), ('return', 'Trả sách'), ('review', 'Đánh giá'), ('reputation_gained', 'Tăng điểm'), ('level_up', 'Lên hạng'), ('login', 'Đăng nhập'), ('view_book', 'Xem sách')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.book')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.librarybus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hoạt động người dùng',
                'verbose_name_plural': 'Hoạt động người dùng',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='analytics_u_user_id_630f80_idx'), models.Index(fields=['activity_type'], name='analytics_u_activit_26a8bf_idx'), models.Index(fields=['created_at'], name='analytics_u_created_775113_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='UserReadingStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('total_books_borrowed', models.PositiveIntegerField(default=0)),
                ('total_books_returned', models.PositiveIntegerField(default=0)),
                ('total_pages_read', models.PositiveIntegerField(default=0)),
                ('reading_streak_days', models.PositiveIntegerField(default=0)),
                ('max_reading_streak', models.PositiveIntegerField(default=0)),
                ('reputation_score', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('member_level', models.CharField(choices=[('bronze', 'Đồng'), ('silver', 'Bạc'), ('gold', 'Vàng'), ('platinum', 'Bạch kim'), ('diamond', 'Kim cương')], default='bronze', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thống kê đọc sách',
                'verbose_name_plural': 'Thống kê đọc sách',
                'indexes': [models.Index(fields=['reputation_score'], name='analytics_u_reputat_f3a7de_idx'), models.Index(fields=['member_level'], name='analytics_u_member__bd6572_idx'), models.Index(fields=['last_activity'], name='analytics_u_last_ac_6c0681_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
    ]
