# Generated by Django 5.2.2 on 2026-07-29 12:39

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('notification_type', models.CharField(db_index=True, default='info', max_length=30, verbose_name='Loại thông báo')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Đã đọc')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đọc')),
                ('action_url', models.URLField(blank=True, verbose_name='URL hành động')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_ff9061_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
    ]
