# Generated by Django 5.2.2 on 2026-08-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
