# Generated by Django 5.2.4 on 2025-07-24 20:36

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Tên lĩnh vực')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('color_code', models.CharField(blank=True, default='#007bff', max_length=7, verbose_name='Mã màu')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('_book_count', models.PositiveIntegerField(default=0, verbose_name='Số sách')),
            ],
            options={
                'verbose_name': 'Lĩnh vực',
                'verbose_name_plural': 'Các lĩnh vực',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='inventory_c_slug_9e1826_idx'), models.Index(fields=['is_active'], name='inventory_c_is_acti_63d81f_idx'), models.Index(fields=['is_active', 'name'], name='inventory_c_is_acti_bad78e_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='LibraryBus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Tên xe bus')),
                ('license_plate', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Biển số xe')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ')),
                ('location_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Tên địa điểm')),
                ('operating_status', models.CharField(choices=[('active', 'Đang hoạt động'), ('parked', 'Tạm nghỉ'), ('maintenance', 'Bảo trì'), ('moving', 'Đang di chuyển')], db_index=True, default='parked', max_length=50, verbose_name='Trạng thái hoạt động')),
                ('capacity', models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)], verbose_name='Sức chứa sách')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại liên hệ')),
                ('operating_hours', models.CharField(blank=True, default='08:00 - 17:00', max_length=100, verbose_name='Giờ hoạt động')),
                ('_book_count', models.PositiveIntegerField(default=0, verbose_name='Số sách hiện tại')),
                ('_last_book_update', models.DateTimeField(auto_now=True, verbose_name='Cập nhật sách lần cuối')),
            ],
            options={
                'verbose_name': 'Xe Bus Sách',
                'verbose_name_plural': 'Các Xe Bus Sách',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['operating_status'], name='inventory_l_operati_f8cb58_idx'), models.Index(fields=['latitude', 'longitude'], name='inventory_l_latitud_ff4e65_idx'), models.Index(fields=['updated_at'], name='inventory_l_updated_45c460_idx'), models.Index(fields=['name', 'operating_status'], name='inventory_l_name_09be8d_idx'), models.Index(fields=['_book_count'], name='inventory_l__book_c_b34a92_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Tên sách')),
                ('author', models.CharField(db_index=True, max_length=200, verbose_name='Tác giả')),
                ('publisher', models.CharField(db_index=True, max_length=200, verbose_name='Nhà xuất bản')),
                ('publication_year', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2026)], verbose_name='Năm xuất bản')),
                ('page_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số trang')),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=13, verbose_name='ISBN')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Ảnh bìa')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='book_pdfs/', verbose_name='File PDF')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('language', models.CharField(db_index=True, default='Tiếng Việt', max_length=50, verbose_name='Ngôn ngữ')),
                ('condition', models.CharField(choices=[('new', 'Mới'), ('like_new', 'Như mới'), ('good', 'Tốt'), ('fair', 'Khá'), ('poor', 'Cũ')], db_index=True, default='good', max_length=20, verbose_name='Tình trạng sách')),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('lost', 'Lost')], db_index=True, default='available', max_length=20)),
                ('last_status_change', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_digital_only', models.BooleanField(db_index=True, default=False, verbose_name='Chỉ có bản điện tử')),
                ('_average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Đánh giá TB')),
                ('_total_borrows', models.PositiveIntegerField(default=0, verbose_name='Tổng lượt mượn')),
                ('_popularity_score', models.FloatField(default=0, verbose_name='Điểm phổ biến')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='inventory.category', verbose_name='Lĩnh vực')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_on_bus', to='inventory.librarybus', verbose_name='Vị trí sách (trên xe bus)')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Các đầu sách',
                'ordering': ['title'],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='BookStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('from_status', models.CharField(db_index=True, max_length=20)),
                ('to_status', models.CharField(db_index=True, max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inventory.book')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái sách',
                'verbose_name_plural': 'Lịch sử trạng thái sách',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['book', '-created_at'], name='inventory_b_book_id_79e309_idx'), models.Index(fields=['from_status', 'to_status'], name='inventory_b_from_st_9dcd88_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Thiếu sách'), ('overstock', 'Thừa sách'), ('popular_demand', 'Nhu cầu cao'), ('maintenance', 'Cần bảo trì')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Nghiêm trọng')], db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.librarybus')),
            ],
            options={
                'verbose_name': 'Cảnh báo tồn kho',
                'verbose_name_plural': 'Cảnh báo tồn kho',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bus', 'is_resolved'], name='inventory_i_bus_id_130588_idx'), models.Index(fields=['alert_type', 'severity'], name='inventory_i_alert_t_66d791_idx'), models.Index(fields=['created_at'], name='inventory_i_created_a12188_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('route_name', models.CharField(db_index=True, max_length=100)),
                ('stops', models.JSONField()),
                ('schedule', models.JSONField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='inventory.librarybus')),
            ],
            options={
                'verbose_name': 'Lộ trình xe bus',
                'verbose_name_plural': 'Lộ trình xe bus',
                'indexes': [models.Index(fields=['bus', 'is_active'], name='inventory_b_bus_id_fa2652_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='inventory_b_status_2a2e34_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', 'status'], name='inventory_b_categor_e2fbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['location', 'status'], name='inventory_b_locatio_1f010f_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='inventory_b_title_cad733_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='inventory_b_author_d1fbf8_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year'], name='inventory_b_publica_7ed28b_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='inventory_b_isbn_aa4998_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='inventory_b_created_d12f31_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['_popularity_score'], name='inventory_b__popula_638797_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', 'category', 'location'], name='inventory_b_status_9293ed_idx'),
        ),
    ]
