# Generated by Django 5.2.2 on 2026-07-29 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2027)], verbose_name='Năm xuất bản'),
        ),
    ]
