# Generated by Django 5.2.2 on 2026-08-03 20:39

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_book_publication_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('book_title', models.CharField(max_length=255, verbose_name='Tên sách quyên góp')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Tác giả')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả / Tình trạng sách')),
                ('status', models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã phê duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Quyên góp sách',
                'verbose_name_plural': 'Quyên góp sách',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='inventory_b_status_07b499_idx'), models.Index(fields=['user', 'status'], name='inventory_b_user_id_d3c5df_idx'), models.Index(fields=['created_at'], name='inventory_b_created_c9aae5_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
    ]
