# Generated by Django 5.2.2 on 2026-08-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdonation',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='donations/books/', verbose_name='File sách đính kèm (nếu có)'),
        ),
    ]
