# Generated by Django 5.2.2 on 2026-08-04 22:34

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_bookdonation_book_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số sao')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='inventory.book', verbose_name='Sách')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đánh giá sách',
                'verbose_name_plural': 'Đánh giá sách',
                'indexes': [models.Index(fields=['book', 'rating'], name='inventory_b_book_id_fb3656_idx'), models.Index(fields=['user'], name='inventory_b_user_id_83452e_idx')],
                'unique_together': {('book', 'user')},
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
    ]
