# Generated by Django 5.2.4 on 2025-07-24 20:36

import core.models
import django.core.validators
import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('theme', models.CharField(choices=[('light', 'Sáng'), ('dark', 'Tối'), ('auto', 'Tự động')], default='light', max_length=10)),
                ('books_per_page', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('auto_renew_books', models.BooleanField(default=False, verbose_name='Tự động gia hạn sách')),
                ('show_reading_progress', models.BooleanField(default=True, verbose_name='Hiển thị tiến độ đọc')),
                ('public_reading_list', models.BooleanField(default=True, verbose_name='Công khai danh sách đọc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tùy chọn người dùng',
                'verbose_name_plural': 'Tùy chọn người dùng',
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Thông tin thiết bị')),
                ('location_info', models.JSONField(blank=True, default=dict, verbose_name='Thông tin vị trí')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Đăng nhập thành công')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử đăng nhập',
                'verbose_name_plural': 'Lịch sử đăng nhập',
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_login_user_id_0a4ab0_idx'), models.Index(fields=['ip_address'], name='users_login_ip_addr_84051d_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ (VD: 0912345678 hoặc +84912345678)', regex='^(\\+84|0)[0-9]{9,10}$')], verbose_name='Số điện thoại')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to=users.models.avatar_upload_path, validators=[users.models.validate_avatar_file_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Ảnh đại diện')),
                ('address', models.TextField(blank=True, max_length=500, verbose_name='Địa chỉ chi tiết')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Thành phố')),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Mã bưu điện')),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác'), ('P', 'Không muốn tiết lộ')], max_length=1, verbose_name='Giới tính')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Nghề nghiệp')),
                ('bio', models.TextField(blank=True, max_length=300, verbose_name='Giới thiệu bản thân')),
                ('membership_level', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], default='basic', max_length=20)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Đã xác thực')),
                ('verification_code', models.CharField(blank=True, max_length=6, verbose_name='Mã xác thực')),
                ('verification_expires', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn mã xác thực')),
                ('preferred_language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='vi', max_length=10, verbose_name='Ngôn ngữ ưa thích')),
                ('reading_goal_monthly', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Mục tiêu đọc sách/tháng')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP đăng nhập cuối')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Số lần đăng nhập')),
                ('privacy_settings', models.JSONField(blank=True, default=dict, verbose_name='Cài đặt riêng tư')),
                ('favorite_categories', models.ManyToManyField(blank=True, related_name='favorite_users', to='inventory.category', verbose_name='Lĩnh vực yêu thích')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
                'indexes': [models.Index(fields=['city', 'district'], name='users_profi_city_d926cc_idx'), models.Index(fields=['date_of_birth'], name='users_profi_date_of_ba4e29_idx'), models.Index(fields=['is_verified', 'is_active'], name='users_profi_is_veri_bfb6b4_idx'), models.Index(fields=['phone_number'], name='users_profi_phone_n_8821cb_idx'), models.Index(fields=['membership_level'], name='users_profi_members_feb5f1_idx'), models.Index(fields=['user', 'is_verified'], name='users_profi_user_id_3cedb2_idx')],
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theo dõi người dùng',
                'verbose_name_plural': 'Theo dõi người dùng',
                'constraints': [models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='no_self_follow')],
                'unique_together': {('follower', 'following')},
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Cập nhật lần cuối')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái hoạt động')),
                ('interest_type', models.CharField(choices=[('author', 'Tác giả'), ('genre', 'Thể loại'), ('topic', 'Chủ đề'), ('publisher', 'NXB')], db_index=True, max_length=20)),
                ('interest_value', models.CharField(max_length=200, verbose_name='Giá trị sở thích')),
                ('weight', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Mức độ quan tâm (1-10)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sở thích người dùng',
                'verbose_name_plural': 'Sở thích người dùng',
                'indexes': [models.Index(fields=['user', 'interest_type'], name='users_useri_user_id_864360_idx')],
                'unique_together': {('user', 'interest_type', 'interest_value')},
            },
            bases=(models.Model, core.models.CacheMixin),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('member', 'Member')], max_length=50)),
                ('scope', models.JSONField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('user', 'role'), name='unique_user_role')],
            },
        ),
    ]
