# Generated by Django 5.2.2 on 2026-07-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='location_info',
        ),
    ]
